# Introduction to `numpy`

This course (and modern deep learning in general) requires the ability to efficiently translate between math and code.

`numpy` is one library in the Python ecosystem that helps with this; later in the course, you might interact also with `torch`, which implements many of the same interfaces and functions, but allows you to take advantage of the GPU for parallelizing matrix operations.

If you have not had much experience with using `numpy`, you can use this notebook to learn the fundamentals, where we've distilled the most essential bits from the [NumPy fundamentals tutorial](https://numpy.org/doc/2.2/user/basics.html).

In [1]:
# it's conventional to alias numpy to np for convenience
import numpy as np

## Foundations

The basic data structure in `numpy` is the `ndarray`. As the name suggests, this is an `n`-dimensional array.

There are many ways to create an array; one way is by wrapping a Python list:

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

We can see that this is an array with dimensionality $(2 \times 3)$. This is called the `shape` in numpy. We can get the shape of any array with `.shape`.

The shape is extremely important! Often, the first step to debugging your numpy or pytorch code is to make sure that the shapes are as you expect.

In [3]:
a.shape

(2, 3)

Arrays have a fixed dimensionality, and must be _homogeneous_. This means all of the elements along a dimension need to be the same shape.

In [4]:
# this does not work!
np.array([[1, 2, 3], [4], [5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

There are also other ways of making arrays. You can read about them [in the documentation](https://numpy.org/doc/2.2/user/basics.creation.html).

You can apply functions to arrays. For example, to find the element-wise square roots:

In [5]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

There are also functions that reduce an array. For example, to calculate the sum:

In [6]:
np.sum(a)

np.int64(21)

Or the mean:

In [7]:
np.mean(a)

np.float64(3.5)

These functions which can reduce an array also take an additional `axis` argument. This specifies the dimension along which to perform the reduction. For example, if we want to find the sum of each row:

In [8]:
np.sum(a, axis=1)

array([ 6, 15])

When first getting started, picking the correct axis can seem counter-intuitive, especially in higher dimensions; this is when it can be useful to think in terms of shapes! 

Recall that the shape of `a` is `(2, 3)`.

In [9]:
a.shape

(2, 3)

You can think of setting `axis=1` as "knocking out" the axis at index 1, so that your final result has a shape of `(2,)`. It can often be helpful to think about what shape your output should be, and set the axes accordingly.

For example, suppose you have a list of 3D points. You want to find the average of all of them in Euclidean space. The initial list would have a shape `(N, 3)`. What shape do you want your result to be? And what, then, should `axis` be set to?

In [10]:
np.random.seed(159259)
points = np.random.random((10, 3))
points

array([[0.82826546, 0.45613847, 0.04542193],
       [0.88322739, 0.62407693, 0.44280589],
       [0.86793313, 0.58903658, 0.78263752],
       [0.46489405, 0.44460684, 0.78668405],
       [0.83910651, 0.01011016, 0.02848037],
       [0.47143244, 0.4240731 , 0.96366351],
       [0.30717807, 0.29191397, 0.67454438],
       [0.88673763, 0.92868206, 0.97077613],
       [0.33542466, 0.39704102, 0.12465267],
       [0.01753313, 0.9362269 , 0.83051909]])

In [11]:
points.mean(axis=0)

array([0.59017325, 0.5101906 , 0.56501855])

## Indexing

We want to be able to access the data in these arrays; numpy supports a rich set of indexing features to make that easier.

In [12]:
# basic:

a[0], a[0][1]

(array([1, 2, 3]), np.int64(2))

In [13]:
# you can also write the second one like this, using commas to separate dimensions
a[0, 1]

np.int64(2)

In [14]:
# we can combine the above with slicing
# here, we take the second item in each row
a[:, 1]

array([2, 5])

Let's make a bigger array with more dimensions!

In [15]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
# Yes, it really is that easy
b.shape = (3, 2, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
# YOUR TURN: How would we get the second column of each inner matrix
# (e.g., we want [[1, 5], [9, 13], [17, 21]])



If, instead of an integer index, you use a sequence of integers, you will index into each of the indices in that list.

This is called _advanced indexing_, and you can read more about it in [the indexing documentation](https://numpy.org/doc/2.2/user/basics.indexing.html#advanced-indexing).

In [18]:
# this takes the 2nd and 3rd items along the last dimension.

b[:, :, [1, 2]]

array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [13, 14]],

       [[17, 18],
        [21, 22]]])

This can be useful to select specific rows.

In [19]:
b.shape = (8, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [20]:
b[[1, 4, 5]]

array([[ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

We can also use indexing to add arbitrary _axes_ (dimensions) to our array.

In [21]:
b.shape = (3, 2, 4)
b.shape

(3, 2, 4)

In [22]:
b[:, :, np.newaxis, :].shape

(3, 2, 1, 4)

Notice how, if we multiply all of these together, we still get 24; regardless of how we shape the array, it always still contains the original 24 items. If we look at the reshaped array, we can see that, while a layer of nesting was added, no new values were added.

In [23]:
b[:, :, np.newaxis, :]

array([[[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]]],


       [[[ 8,  9, 10, 11]],

        [[12, 13, 14, 15]]],


       [[[16, 17, 18, 19]],

        [[20, 21, 22, 23]]]])

It can be useful to add new axes or reshape an array because numpy supports a powerful concept to _vectorize_ array operations (apply the same operation across many elements in an array): **broadcasting**.

## Broadcasting

Let us start with a simple, non-broadcasting example, then build up the motivation.

In [24]:
a = np.array([1, 2, 3, 4])
b = np.ones_like(a)

print("a =", a, "; b =", b)

a = [1 2 3 4] ; b = [1 1 1 1]


In [25]:
a + b

array([2, 3, 4, 5])

As we might have hoped, `a` and `b` are summed element-wise.

But how would this work if they are not the same shape? It doesn't!

In [26]:
b = np.array([1, 1])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

However, we might intuitively expect some operations to succeed even if the shapes don't match.

For example:

In [27]:
b = 1  # b is a scalar
a + b

array([2, 3, 4, 5])

And this matches our intuitions! Even though `a` and `b` don't have the same shape, `numpy` knows to _broadcast_ this operation across all the elements of `a`. As the [documentation points out](https://numpy.org/doc/2.2/user/basics.broadcasting.html#:~:text=We%20can%20think%20of%20the%20scalar%20b%20being%20stretched%20during%20the%20arithmetic%20operation%20into%20an%20array%20with%20the%20same%20shape%20as%20a%2E), you can imagine that `b` is _stretched_ into an array that matches the shape of `a`.

Not only is this cleaner, it is also more efficient, because we need not allocate redundant memory for `b`. But how does `numpy` decide where to stretch?

From the documentation:
> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
> 1. they are equal, or
> 2. one of them is 1.
> 
> If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes.

Let's look at an example.

In [28]:
a = np.arange(15)
a.shape = (3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
b = np.arange(3)
b

array([0, 1, 2])

In [30]:
a.shape

(3, 5)

In [31]:
b.shape

(3,)

Following the numpy rules, we line up the shapes starting from right to left:
```
A (2d array): 3 x 5
B (1d array):     3
```
Since the rightmost dimensions do not match, these are incompatible, and cannot be broadcast! And, indeed, we get an error.

In [32]:
a * b

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

But, if we reshape `b`, we have a chance. Consider the following scenario:

```
A (2d array): 3 x 5
B (2d array): 3 x 1
```

Now, the rightmost dimension is compatible because one of them is a 1. The next dimension is also compatible because both are equal to 3.

In [75]:
a * b.reshape(3, 1)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28]])

And it works!

This also gives us a better look at _how_ `b` is being broadcast: it is being repeated 5 times along the last axis.

Let's look at one more slightly more complex example:

In [80]:
a = np.arange(32).reshape(4, 2, 4)
b = np.arange(16).reshape(4, 4)

How can we broadcast `b`?

In [84]:
# TODO: what shape should `b` be?

a * b.reshape(???)

TypeError: reshape() takes exactly 1 argument (0 given)

You can imagine that broadcasting might be useful if you, for example, trying to compare one thing to multiple things. Consider the Euclidean distance function $$
d(\vec{x}, \vec{y}) = \sqrt{\sum_{i}({x_i} - {y_i})^2}
$$

We might want to calculate the distance between one point and a set of points.

In [108]:
point = np.array([0, 0.5, 0.2])

other_points = np.array([
    [1, 9, 3],
    [0.2, 0.8, 0.4],
    [-2, 0.1, 0.5],
    [2, 0.1, 0.5]
])

Let's start by writing out what the calculation would be like for comparing to just one other point. Perhaps the first one:

In [109]:
np.sqrt(np.sum((point - other_points[0]) ** 2))

np.float64(9.004998611882181)

We can see this works because `point` has shape `(3,)` and `other_points[0]` also has shape `(3,)`. All of the other operations just apply element-wise (or reduce over the whole array, in the case of `np.sum`).

How about the whole list?

In [110]:
np.sqrt(np.sum((point - other_points) ** 2))

np.float64(9.47417542586161)

We expected an array of 3 distances, but instead we only get a single scalar output. Why?

Notice that we have an `np.sum` that reduces over the entire array. While this is what we wanted when comparing just two points, it is now summing over not only within each vector, but also across all the vectors.

In [113]:
(point - other_points).shape

(4, 3)

We want as output a shape `(4,)` array that contains the sum for each row in `other_points`. So, we apply `sum` along `axis=1`.

In [114]:
np.sqrt(np.sum((point - other_points) ** 2, axis=1))

array([9.00499861, 0.41231056, 2.06155281, 2.06155281])

And now we get our desired output!

To learn more about broadcasting, you can consult [the numpy documentation](https://numpy.org/doc/2.2/user/basics.broadcasting.html#broadcasting).

## Wrapping up

It is extremely important to get comfortable working in multiple dimensions and thinking in terms of shapes. The skills you develop with numpy now will almost directly transfer to working with Pytorch later in the semester (and into the future!)